services:
  php:
    image: ${REGISTRY}/${PHP_IMAGE_NAME}:${TAG:-latest}
    container_name: symfony_php
    restart: unless-stopped
    networks:
      - symfony_network
    depends_on:
      - redis
    volumes:
      - .env:/var/www/html/.env:ro
      - ./data/symfony-logs:/var/www/html/var/log
      - ./data/symfony-cache:/var/www/html/var/cache
      - ./data/uploads:/var/www/html/public/uploads

  nginx:
    image: ${REGISTRY}/${NGINX_IMAGE_NAME}:${TAG:-latest}
    container_name: symfony_nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    networks:
      - symfony_network
    depends_on:
      - php
      - redis
    volumes:
      - ./data/nginx-logs:/var/log/nginx
      - ./data/uploads:/var/www/html/public/uploads:ro

  redis:
    image: redis:alpine
    container_name: symfony_redis
    restart: unless-stopped
    networks:
      - symfony_network
    volumes:
      - redis_data:/data

networks:
  symfony_network:
    driver: bridge

volumes:
  redis_data:
