services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    container_name: ${COMPOSE_PROJECT_NAME}_api
    command: ["sh", "-c", "/usr/local/bin/start.sh"]
    restart: on-failure
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/supervisord.conf:/etc/supervisor/supervisord.conf
    networks:
      - symfony-network
    ports:
      - "9000:9000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    command: ["sh", "-c", "if [ ! -d 'node_modules' ]; then npm install; fi && npm run dev"]
    working_dir: /app
    volumes:
      - ./frontend:/app:cached
    environment:
      - VITE_API_URL=http://api.symfony.local
    ports:
      - "5173:5173"
    depends_on:
      - php
    networks:
      - symfony-network

  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - node
    networks:
      - symfony-network

  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony-network

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 60s
    ports:
      - "6379:6379"
    networks:
      - symfony-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    restart: on-failure
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - symfony-network

  adminer:
    image: adminer
    container_name: symfony_adminer
    ports:
      - "8080:8080"
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge

volumes:
  mysql_data:
